[project]
name = "summaryretriever"
version = "0.1.0"
requires-python = ">=3.10"
dependencies = [
    "langchain>=0.3,<0.4",
    "langchain-core>=0.3,<0.4",
    "langchain-huggingface>=0.3",
    "langchain-chroma>=0.2",
    "ragas>=0.3",
    "sentence-transformers>=5.6.1",
    "python-docx>=1.2.0",
    "load-dotenv>=0.1.0",
    "langgraph>=1.0.1",
    "create-agent>=0.0.3",
]
